-- ═══════════════════════════════════════════════════════════════
-- LightCenter.kz — таблица заявок (мини-CRM)
-- Запусти в Supabase → SQL Editor → Run. Идемпотентно.
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.leads (
  id         bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  type       text default 'lead',      -- order / cart / lead / b2b / contact
  order_id   text,
  name       text,
  phone      text,
  message    text,
  product    text,
  amount     integer,
  status     text not null default 'new'  -- new / called / done
);

create index if not exists leads_created_idx on public.leads (created_at desc);
create index if not exists leads_status_idx  on public.leads (status);

-- Доступ: читать/менять/удалять — только после входа в админку.
-- Вставку делает серверная функция send-lead (service role, минуя RLS).
alter table public.leads enable row level security;
drop policy if exists "auth read leads"   on public.leads;
drop policy if exists "auth update leads" on public.leads;
drop policy if exists "auth delete leads" on public.leads;
create policy "auth read leads"   on public.leads for select to authenticated using (true);
create policy "auth update leads" on public.leads for update to authenticated using (true) with check (true);
create policy "auth delete leads" on public.leads for delete to authenticated using (true);

select count(*) as leads_count from public.leads;
